<?php $this->headTitle('About'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>About</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <p>
              <strong>Zend Framework 3</strong> is an open source framework for PHP developers. It can be used to develop web applications and services using PHP 5.5+. Zend Framework is 100% object-oriented code with most of the new features of PHP 5.5, namely namespaces, late static binding, lambda functions and closures.
              It uses <a href="https://getcomposer.org/">composer</a> as dependency package manager and it follows the <a href="http://www.php-fig.org/">PHP-FIG</a> standards, including the <a href="http://www.php-fig.org/psr/psr-7/">PSR-7</a> for HTTP messages interfaces proposed by <a href="https://mwop.net/">Matthew Weier O'Phinney</a>, team leader of Zend Framework.
            </p>
            <p>
              <strong>Zend Framework 3</strong> evolved from Zend Framework 2 and 1, previous versions with over 15 million downloads.
            </p>
            <p>
              We use <a href="https://phpunit.de/">PHPUnit</a> to test our code and <a href="https://travis-ci.org/">Travis CI</a> as a Continuous Integration service.
            </p>

            <p>
              The principal sponsor of Zend Framework is <a href="http://www.zend.com">Zend</a>, a Rogue Wave Company, but many others have contributed components or significant features to the framework. Companies such as Google, Microsoft, and StrikeIron have partnered with Zend to provide interfaces to web services and other technologies they wish to make available to ZF developers.
            </p>

            <p>
              <strong>Zend Framework 3</strong> could not deliver and support all of these features without the help of the vibrant community. Community members, including contributors, make themselves available on mailing lists, IRC channels and other forums. Whatever question you have about Zend Framework, the community is always available to address it.
            </p>
        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::about-menu', [ 'active' => '/about' ]) ?>
        </div>
    </div>
</div>
