<?php $this->headTitle('Advisory'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Security Advisory: <?php echo $advisory ?></h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <p>
              <?php echo $body ?>
            </p>
            <div class="spacing"></div>
            <p>Released <?php echo date("l m, Y", $date) ?></p>
            <p><a href="/security/advisories"><i class="fa fa-chevron-left"></i> Back to advisories</a></p>
        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::security-menu') ?>
        </div>
    </div>
</div>
