<?php $this->headTitle('Security')->prepend('Security Advisories'); ?>

            <h2>Security Advisories</h2>
            <h3>Vulnerabilities reported against Zend Framework, and recommendations for mitigation</h3>

            <div class="spacing"></div>

            <div class="list-group">
            <?php foreach ($advisories as $key => $advisory) : ?>
                <a class="list-group-item" href="/security/advisory/<?= basename($key, '.md') ?>">
                    <h4 class="list-group-item-heading"><i class="fa fa-bug"></i>&nbsp;<?= $advisory['title'] ?></h4>
                    <p class="list-group-item-text">Published <?= date('Y-m-d', $advisory['date']) ?></p>
                </a>
            <?php endforeach ?>
            </div>

            <div class="spacing"></div>
            <div class="hline"></div>

            <ul class="pager">
                <li class="previous<?= $prev ? '' : ' disabled' ?>"><a href="<?= $prev ? '?page=' . $prev : '#' ?>"><i class="fa fa-chevron-left"></i>&nbsp;Previous</a></li>
                <li><strong class="text-info"><?php printf("Page %d/%d", $page, $tot) ?></strong></li>
                <li class="next<?= $next ? '' : ' disabled' ?>"><a href="<?= $next ? '?page=' . $next : '#' ?>">Next&nbsp;<i class="fa fa-chevron-right"></i></a></li>
            </ul>

        <?php $this->placeholder('sub-navigation')->set(
            $this->render('include::security-menu')
        ) ?>
