<?php $this->headTitle('Security')->prepend('Security Advisory'); ?>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Security Advisory: <?= $advisory ?></h2>

            <?= $body ?>

            <div class="spacing"></div>
            <div class="hline"></div>

            <p>Released <?= date('Y-m-d', $date) ?></p>
            <p><a href="/security/advisories"><i class="fa fa-chevron-left"></i> Back to advisories</a></p>
        </div>

        <?php $this->placeholder('sub-navigation')->set(
            $this->render('include::security-menu')
        ) ?>
    </div>
</div>
