<?php $this->headTitle('Changelog'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>About</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Changelog</h2>

            <h3><?= $changelog ?> (<?= date("Y-m-d", $date) ?>)</h3>

            <select id="version" class="form-control" onchange="window.location='/changelog/' + this.options[this.selectedIndex].value">
            <?php foreach ($versions as $ver) : ?>
              <option value="<?= $ver ?>" <?= ($ver == $changelog) ? 'selected' : '' ?>><?= $ver ?></option>
            <?php endforeach; ?>
            </select>

            <p><?= $body ?></p>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::about-menu', [ 'active' => '/changelog' ]) ?>
        </div>
    </div>
</div>
