<?php $this->headTitle('Participate')->prepend('Code Manifesto'); ?>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Code Manifesto</h2>
            
            <p>We have adopted the <a href="http://codemanifesto.com/">Code Manifesto</a> in the Zend Framework organization.</p>

            <p>We want to work in an ecosystem that empowers developers to reach their potential--one that encourages professional growth and effective collaboration. A space that is safe for all.</p>

            <p>A space such as this benefits everyone that participates in it. It encourages new developers to enter our field. It is through discussion and collaboration that we grow, and through growth that we improve.</p>

            <p>In the effort to create such a place, we hold to these values:</p>

            <ol>
                <li><strong>Discrimination limits us.</strong> This includes discrimination on the basis of race, gender, sexual orientation, gender identity, age, nationality, technology and any other arbitrary exclusion of a group of people.</li>
                <li><strong>Boundaries honor us</strong>. Your comfort levels are not everyone’s comfort levels. Remember that, and if brought to your attention, heed it.</li>
                <li><strong>We are our biggest assets</strong>. None of us were born masters of our trade. Each of us has been helped along the way. Return that favor, when and where you can.</li>
                <li><strong>We are resources for the future.</strong> As an extension of #3, share what you know. Make yourself a resource to help those that come after you.</li>
                <li><strong>Respect defines us</strong>. Treat others as you wish to be treated. Make your discussions, criticisms and debates from a position of respectfulness. Ask yourself, is it true? Is it necessary? Is it constructive? Anything less is unacceptable.</li>
                <li><strong>Reactions require grace</strong>. Angry responses are valid, but abusive language and vindictive actions are toxic. When something happens that offends you, handle it assertively, but be respectful. Escalate reasonably, and try to allow the offender an opportunity to explain themselves, and possibly correct the issue.</li>
                <li><strong>Opinions are just that: opinions</strong>. Each and every one of us, due to our background and upbringing, have varying opinions. The fact of the matter, is that is perfectly acceptable. Remember this: if you respect your own opinions, you should respect the opinions of others.</li>
                <li><strong>To err is human</strong>. You might not intend it, but mistakes do happen and contribute to build experience. Tolerate honest mistakes, and don't hesitate to apologize if you make one yourself.</li>
            </ol>

            <p>More information about the Code Manifesto are available at <a href="http://codemanifesto.com/">codemanifesto.com</a></p>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::participate-menu', [ 'active' => '/participate/code-manifesto' ]) ?>
        </div>
    </div>
</div>
