<?php $this->headTitle('Participate')->prepend('Contributor Guide'); ?>

<h2>Contributor Guide</h2>
<h3>Have something you want to contribute back?</h3>

<p>
    In the spirit of open-source software, you can contribute as
    little or as much as you like: bug reports, patches, full
    components or documentation are all equally appreciated. The
    following section describes contributing to Zend Framework.
</p>

<h3>So, You Want to File A Bug Report ...</h3>

<p>
    So, you've found what you think might be a bug. Before you file
    it, we'd ask that you ensure that what you have is indeed a
    bug, by doing a little due-diligence (which also is good
    information to add to the bug report):
</p>

<ul>
    <li>see if your use case is covered in the <a href="/learn">documentation</a>;</li>
    <li>search the <a href="/issues">issue trackers</a> for your particular use case;</li>
    <li>discuss your issue with someone on the <a href="https://zendframework-slack.herokuapp.com">Slack channel</a>;</li>
    <li>write a failing test case using <a href="https://phpunit.de/">PHPUnit</a>.</li>
</ul>

<p>
    You don't have to do all of those, but by doing a few of them,
    it helps ensure that your bug report is complete and will get tended to.
</p>

<p>
    When you're finally ready:<br/>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#issueModal">Submit an issue</button>
</p>

<h3>So, You Want to Contribute Code ...</h3>

<p>
    By and large, this framework is built and maintained by the
    community. This means that process for submitting something
    back, be it a patch, some documentation, or new feature
    requires some level of community interaction.
    We proudly host our code on <a href="https://github.com/zendframework">GitHub</a>.
</p>

<p>
    If you're not already familar with git or GitHub, take a moment
    to read through our <a href="https://github.com/zendframework/maintainers/blob/master/CONTRIBUTORS.md">CONTRIBUTING.md</a>.
    The steps to create a patch are:
</p>

<ul>
    <li><strong>fork</strong> the zend-<i>name</i> project (where <i>name</i> is the component you are interested);</li>
    <li>create a local development <strong>branch</strong> for the bugfix;</li>
    <li><strong>commit</strong> a change and <strong>push</strong> your local branch to your github fork;</li>
    <li>send us a <strong>pull request</strong> for your changes to be included.</li>
</ul>

<h3>So, You Want to Hang-out With A Great Community ...</h3>

<h4>Conferences</h4>

<ul>
    <li><a href="http://zendcon.com">ZendCon</a> happens annually, typically in October in the United States.</li>
    <li>Search for <a href="https://joind.in/search?keyword=Zend">Zend Framework talks on joind.in</a></li>
</ul>

<h4>Zend Framework Slack</h4>

<ul>
    <li><a href="https://zendframework-slack.herokuapp.com">Signup
        for an invitation</a></li>
    <li>
        <a href="https://zendframework.slack.com">Zend Framework Slack</a>
        <ul>
            <li><a href="https://zendframework.slack.com/messages/C4QBQUEG5">#general</a> channel (general discussion)</li>
            <li><a href="https://zendframework.slack.com/messages/C4R13GTRD">#contributors</a> channel (discussions relating to the development of Zend Framework itself)</li>
            <li><a href="https://zendframework.slack.com/messages/C4RF4G6LE">#apigility</a> channel (discussion)</li>
            <li><a href="https://zendframework.slack.com/messages/C4RF4P0A2">#apigility-contrib</a> channel (contributor discussion)</li>
            <li><a href="https://zendframework.slack.com/messages/C4RF57B0E">#expressive</a> channel (discussion)</li>
            <li><a href="https://zendframework.slack.com/messages/C4QRP8ELU">#expressive-contrib</a> channel (contributor discussion)</li>
        </ul>
    </li>
    <li><a href="https://zendframework.slackarchive.io">Archives</a></li>
</ul>

<h4>Forums (Discourse)</h4>

<p>
    The generous folks at <a href="https://www.discourse.org">Discourse</a>
    host a dedicated Zend Framework forum:
</p>

<ul>
    <li><a href="https://discousrse.zendframework.com">https://discousrse.zendframework.com</a></li>
</ul>

<p>
    Use this forum to ask questions, particularly around usage, configuration, etc.
    Do _not_ use it to report issues, unless you discover an issue in the process
    of discussing a question; if you _do_ discover an issue, please then
    follow-up by creating an issue in the relevant repository as detailed in
    the section above entitled "So, you think you found a bug".
</p>

<p>
    We have created the following categories:
</p>

<ul>
    <li><a href="https://discourse.zendframework.com/t/welcome-to-the-zend-framework-discussion-forum/8">Welcome page, detailing policy and useful links.</a></li>
    <li><a href="https://discourse.zendframework.com/c/questions/components">Component/zend-mvc application questions</a></li>
    <li><a href="https://discourse.zendframework.com/c/questions/expressive">Expressive Questions</a></li>
    <li><a href="https://discourse.zendframework.com/c/questions/apigility">Apigility Questions</a></li>
    <li><a href="https://discourse.zendframework.com/c/contributors">Contributors section (questions about architecture, milestones, etc.)</a></li>
</ul>

<h4>Newsletter</h4>

<p>If you want to get the latest news delivered straight to your inbox, consider subscribing to our contributor newsletter!</p>

<ul>
    <li><a href="https://tinyletter.com/mwopzend">Signup to receive the newsletter</a></li>
    <li><a href="https://tinyletter.com/mwopzend/archive">Archives</a></li>
</ul>

<?php $this->placeholder('sub-navigation')->set(
    $this->render('include::participate-menu', ['active' => '/participate/contributor-guide'])
) ?>

<?= $this->render('include::modal-issue', ['repository' => $repository]); ?>
