<?php $this->headTitle('Participate'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Contributors</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
          <h2>Contributors</h2>
        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::participate-menu', [ 'active' => '/participate/contributors' ]) ?>
        </div>
      </div>
  </div>
