<?php $this->headTitle('Participate'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Participate</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Contributors</h2>

            <p>
                Zend Framework is an open source project sponsored by
                <a href="http://www.zend.com">Zend Technologies</a>, a
                <a href="http://www.roguewave.com">Rogue Wave Company</a>.
            </p>

            <p>
                The Zend team working on the project is composed of
                 <a href="https://mwop.net/">Matthew Weier O'Phinney</a>, Principal Engineer and Project Lead, and
                <a href="http://www.zimuel.it/">Enrico Zimuel</a>, Senior Software Engineer.
            </p>

            <div class="row">
                <div class="col-sm-12 col-lg-6 center-text">
                    <a href="https://mwop.net/"><img src="/img/matthew.jpg" alt="Matthew Weier O'Phinney" title="Matthew Weier O'Phinney"><br />
                    Matthew Weier O'Phinney</a>, ZF Team Lead
                </div>

                <div class="col-sm-12 col-lg-6 center-text">
                    <a href="http://www.zimuel.it/"><img src="/img/enrico.jpg" alt="Enrico Zimuel" title="Enrico Zimuel"><br />
                    Enrico Zimuel</a>, ZF Core Developer
                </div>
            </div>

            <p>
                Zend Framework development and maintenance has been provided by
                <strong>almost 700 volunteers</strong>. You can view the various
                contributors via the "Contributors Graph" of each component;
                <a href="https://github.com/zendframework/zendframework/graphs/contributors">the 
                majority are listed via the zendframework/zendframework repository.</a>
            </p>

            <p>The project is in part governed by our <strong>Community Review Team</strong>:</p>

            <div class="spacing"></div>

            <div class="row">
            <?php foreach ($this->reviewTeam as $name => $url) : ?>
                <div class="col-sm-12 col-lg-4 center-text community-review-team">
                    <a href="<?= $url['web'] ?>"><img src="<?= $url['img'] ?>" alt="<?= $name ?>" title="<?= $name ?>" height="180" width="180"></a><br />
                    <i class="fa fa-github" aria-hidden="true"></i> <a href="<?= $url['web'] ?>"><?= $name ?></a>
                </div>
            <?php endforeach ?>
            </div>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::participate-menu', [ 'active' => '/participate/contributors' ]) ?>
        </div>
    </div>
</div>
