<?php $this->headTitle('Home'); ?>

<div id="headerwrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
              <img src="img/superzf.png" align="right" title="ZF Hero!" alt="ZF Hero!">
            </div>
            <div class="col-lg-8">
              <h1>Zend Framework 3</h1>
              <h3>Professional PHP packages ready for <a href="http://www.zend.com/en/resources/php-7">PHP 7</a><br />Focused on Simplicity, Reusability and Performance</h3>
              <?php if ($stats > 0): ?>
                <h2><?php echo number_format($stats); ?> installs from <a href="https://packagist.org/search/?search_query[query]=zendframework/zend">Packagist</a>!</a></h2>
              <?php endif; ?>
              <p><br /><a href="/downloads" class="btn btn-theme">Get started!</a></p>
            </div>
        </div>
    </div>
</div>

<div id="service">
    <div class="container">
        <div class="row centered">
            <div class="col-md-3">
                <i class="fa fa-dashboard"></i>
                <h4>High Performing</h4>
                <p>Engineered with performance tuning in mind. Zend Framework 3 runs up to 4x than previous version.</p>

            </div>
            <div class="col-md-3">
                <i class="fa fa-gears"></i>
                <h4>Extensible</h4>
                <p>Open architecture based on Middleware or MVC. <a href="http://www.php-fig.org/">PHP-FIG</a> standard compliant.</p>

            </div>
            <div class="col-md-3">
                <i class="fa fa-lock"></i>
                <h4>Secure</h4>
                <p>Built with security best practices in place. Store password using <a href="https://en.wikipedia.org/wiki/Bcrypt">bcrypt</a> and encrypt with <a href="https://it.wikipedia.org/wiki/Advanced_Encryption_Standard">AES-256</a>.</p>

            </div>
            <div class="col-md-3">
                <i class="fa fa-building-o"></i>
                <h4>Enterprise Ready</h4>
                <p>A proven history of success running business critical and high-usage applications. Ready for <a href="http://www.zend.com/en/resources/php-7">PHP 7</a>.</p>

            </div>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">

        <div class="col-lg-4">
            <h4>Latest blog posts <small>( <a href="/blog">full list</a> )</small></h4>
            <div class="hline"></div>
            <?php foreach($posts as $post): ?>
                <p><a href="<?php echo $post['permalink'] ?>"><?php echo $post['title'] ?></a></p>
            <?php endforeach; ?>
        </div>
        <div class="col-lg-5">
            <h4>Latest security advisories <small>( <a href="/security/advisories">full list</a> )</small></h4>
            <div class="hline"></div>
            <?php foreach($advisories as $key => $advisor): ?>
                <p><a href="/security/advisory/<?php echo basename($key, '.md') ?>"><?php echo $advisor['title'] ?></a></p>
            <?php endforeach; ?>
        </div>
        <div class="col-lg-3">
            <h4>Issues and Security</h4>
            <div class="hline"></div>
            <p><i class="fa fa-github fa-2x"></i> Did you find an issue in Zend Framework?<br />
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#issueModal" style="width:100%">Please report here!</button><br />
            <div class="spacing"></div>
            <p><i class="fa fa-bug fa-2x"></i> Did you find a security vulnerability in ZF?
            Please report it to us at <a href="mailto:zf-security@zend.com">zf-security@zend.com</a></p>
        </div>
    </div>
    <div class="spacing"></div>
</div>

<?php echo $this->render('include::modal-issue', [ 'repository' => $repository ]); ?>

<div id="zendcon">
    <div class="container centered">
        <div class="row">
          <div class="col-lg-12">
              <h2>Welcome to ZendCon 2016, October 18-21, Las Vegas</h2>
              <div class="spacing"></div>
              <a href="http://www.zendcon.com"><img src="img/zendcon.png" alt="ZendCon 2016" title="ZendCon 2016"></a>
          </div>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-12">
            <h2 align="center">Maximize Development Productivity</h2>
            <div class="hline"></div>
            <div class="spacing"></div>
            <div class="row">
                <div class="col-lg-4 centered">
                  <img src="/img/ag-hero.png"><br />
                  <p>The easiest way to create high-quality APIs</p>
                  <a href="https://apigility.org" class="btn btn-theme btn-sm">Learn more</a>
                </div>
                <div class="col-lg-4 centered">
                  <img src="/img/zray.png">
                  <p>The Ultimate PHP Productivity Solution</p>
                  <a href="http://www.zend.com/en/products/server/z-ray" class="btn btn-theme btn-sm">Learn more</a>
                </div>
                <div class="col-lg-4 centered">
                  <img src="/img/zend-studio.png">
                  <p>The PHP IDE for Smarter Development</p>
                  <a href="http://www.zend.com/en/products/studio" class="btn btn-theme btn-sm">Learn more</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="twrap">
    <div id="twrapback"></div>
    <div class="container centered">
        <div class="row">
            <div class="col-lg-12">
                <h1 align="center">Get certified!</h1>
                <h4>Becoming a Zend Certified Engineer is a measure of your experience in the world of PHP.</h4>
                <h4>Take a look at the specific PHP and Zend Framework certifications.</h4>
            </div>
        </div>
        <div class="spacing"></div>
        <div class="row">
            <div class="col-lg-4">
                <a href="http://www.zend.com/en/services/certification"><img src="img/phpcert.png" alt="Zend Certified PHP Engineer" title="Zend Certified PHP Engineer"></a>
            </div>
            <div class="col-lg-4">
                <a href="http://www.zend.com/en/services/certification"><img src="img/zf2cert.png" alt="Zend Framework 2 Certified Architect" title="Zend Framework 2 Certified Architect"></a>
            </div>
            <div class="col-lg-4">
                <a href="http://www.zend.com/en/services/certification"><img src="img/zf1cert.png" alt="Zend Framework 1 Certified Engineer" title="Zend Framework 1 Certified Engineer"></a>
            </div>
        </div>
    </div><!-- --/container ---->
</div>

<div id="portfoliowrap">
    <div class="portfolio-centered">
        <h2>Who uses Zend Framework?</h2>
        <div class="recentitems portfolio">
            <?php foreach($projects as $project): ?>
                <div class="portfolio-item graphic-design">
                    <div class="he-wrap tpl6">
                    <img src="/img/clients/<?= $project['img']; ?>" alt="">
                        <div class="he-view">
                            <div class="bg a0" data-animate="fadeIn">
                                <h3 class="a1" data-animate="fadeInDown"><?= $project['name']; ?><br /><font size="-1">(<?= $project['country']; ?>)</font></h3>
                                <a href="<?= $project['url']; ?>" class="dmbutton a2" data-animate="fadeInUp"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
(function($) {
	"use strict";
	var $container = $('.portfolio'),
		$items = $container.find('.portfolio-item'),
		portfolioLayout = 'fitRows';

		if( $container.hasClass('portfolio-centered') ) {
			portfolioLayout = 'masonry';
		}

		$container.isotope({
			filter: '*',
			animationEngine: 'best-available',
			layoutMode: portfolioLayout,
			animationOptions: {
			duration: 750,
			easing: 'linear',
			queue: false
		},
		masonry: {
		}
		}, refreshWaypoints());

		function refreshWaypoints() {
			setTimeout(function() {
			}, 1000);
		}

		$('nav.portfolio-filter ul a').on('click', function() {
				var selector = $(this).attr('data-filter');
				$container.isotope({ filter: selector }, refreshWaypoints());
				$('nav.portfolio-filter ul a').removeClass('active');
				$(this).addClass('active');
				return false;
		});

		function getColumnNumber() {
			var winWidth = $(window).width(),
			columnNumber = 1;

			if (winWidth > 1200) {
				columnNumber = 5;
			} else if (winWidth > 950) {
				columnNumber = 4;
			} else if (winWidth > 600) {
				columnNumber = 3;
			} else if (winWidth > 400) {
				columnNumber = 2;
			} else if (winWidth > 250) {
				columnNumber = 1;
			}
				return columnNumber;
			}

			function setColumns() {
				var winWidth = $(window).width(),
				columnNumber = getColumnNumber(),
				itemWidth = Math.floor(winWidth / columnNumber);

				$container.find('.portfolio-item').each(function() {
					$(this).css( {
					width : itemWidth + 'px'
				});
			});
		}

		function setPortfolio() {
			setColumns();
			$container.isotope('reLayout');
		}

		$container.imagesLoaded(function () {
			setPortfolio();
		});

		$(window).on('resize', function () {
		  setPortfolio();
	  });
})(jQuery);
<?php $this->inlineScript()->captureEnd(); ?>
