<?php $this->headTitle('Install'); ?>

<h2>Get started</h2>

<p>Installation of Zend Framework is only a <a href="http://getcomposer.org">Composer</a> command away:</p>

<pre><code class="lang-bash" data-trim>$ composer require zendframework/zendframework</code></pre>

<p>
    This will install all <strong><?= count($require) - 1 ?></strong>
    packages required in <a href="<?= $composerUrl ?>">composer.json</a>.
    Alternately, all Zend Framework packages can be installed individually; for
    instance, if you need only the MVC package, you can install with the following
    command:
</p>

<pre><code class="lang-bash">$ composer require zendframework/zend-mvc</code></pre>

<p>A list of all the packages can be found in the <a href="/learn">documentation page</a>.</p>

<h2>Zend Server</h2>

<p>
    If you are looking for a professional solution with monitoring
    and root-cause analysis, job queues, code tracing, caching,
    etc., you can download the <strong>30-day trial, free edition
        of Zend Server</strong>.
</p>

<div class="server-download">
    <div class="zend-blocks">
        <img src="/images/ZF-Server-boxes-120x185px.png" alt="Boxes">
    </div>

    <div class="server-content">
        Try <span class="product">Zend Framework</span> with
        <nobr><span class="product">Z-Ray</span></nobr>
        <br>
        in the <span class="promo">30-day Trial Edition</span> of

        <br>

        <img alt="Zend Server" src="/images/Zend-Server-logo-368x51px.png" class="server-logo">

        <br>
        the Professional PHP Distribution

        <br>

        <a href="http://www.zend.com/en/products/server/downloads?utm_source=zfd">
            <img alt="Try Now" src="/images/Try-Now-button-135x39px.png">
        </a>
    </div>
</div>

<?php $this->placeholder('sub-navigation')->set(
    $this->render('include::download-menu', ['active' => '/downloads'])
) ?>
