<?php $this->headTitle('Issues'); ?>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Overview</h2>

            <p>
                Zend Framework manages issues on <a target="_blank" href="https://github.com/zendframework">GitHub</a>.
                In order to <strong>create</strong> an issue, or <strong>browse active issues</strong>,
                you should visit the appropriate project page.
            </p>

            <div class="panel panel-default panel-component toggle">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Active Issue Trackers
                        <span class="pull-right">(click to toggle)</span>
                    </h4>
                </div>

                <div class="list-group hidden">
                <?php foreach ($repository as $component) : ?>
                    <a class="list-group-item" href="https://github.com/zendframework/<?= basename($component['url']) ?>/issues"><?= basename($component['url']) ?></a>
                <?php endforeach ?>
                </div>
            </div>

            <div class="panel panel-default panel-component">
                <div class="panel-heading">
                    <h4 class="panel-title">Archived Issues</h4>
                </div>
                
                <div class="panel-body">
                    As we migrated our issues system to GitHub from another system, we are
                    providing a <strong>read-only, static listing</strong> of archived issues
                    and patches for all issues not migrated to the new system (generally
                    because they have already been resolved, or due to age). You may browse or
                    search those on the following pages:
                </div>

                <ul class="list-group">
                    <li class="list-group-item"><a href="/issues/ZF2">Zend Framework 2 issue archive</a></li>
                    <li class="list-group-item"><a href="/issues/ZF1">Zend Framework 1 issue archive</a></li>
                </ul>
            </div>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::issue-menu') ?>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart() ?>
(function ($) {
    "use strict";

    var componentLink = $('.panel-component.toggle .panel-title');
    var componentList = $('.panel-component.toggle .list-group');

    componentLink.click(toggle);

    function toggle () {
        if (componentList.hasClass('hidden')) {
            componentList.removeClass('hidden');
            componentList.addClass('show');
            return;
        }
        componentList.removeClass('show');
        componentList.addClass('hidden');
    }
})(jQuery);
<?php $this->inlineScript()->captureEnd() ?>
