<?php $this->headTitle('Issue'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3><?php echo $id ?>: <?php echo $title ?></h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <p>
              <?php echo $body ?>
            </p>
        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::issue-menu') ?>
        </div>
    </div>
</div>
