<?php $this->headTitle('Issue'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Issues</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <?= $body ?>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::issue-menu') ?>
        </div>
    </div>
</div>
