<?php $this->headTitle('Learn'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Documentation</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <p>
                <strong>Zend Framework</strong> is a collection of <b>60+ packages</b> for
                professional PHP development.  Each package is available on
                <a href="https://github.com/zendframework">GitHub</a> and can be installed via
                <a href="https://getcomposer.org">Composer</a>.
            </p>

        <div class="col-md-11 panel panel-default">
            <h3><a href="https://docs.zendframework.com/tutorials/">Tutorials</a></h3>
            
            <p>
                We provide tutorials for getting started with zend-mvc,
                understanding advanced topics of many components, and migration
                from version 2 to version 3.
            </p>
        </div>

        <?php
        // add the buttons as reported here: https://gist.github.com/xtreamwayz/010c5e42e7b61559811260c5d14303e4
        reset($components);
        while ($comp = next($components)) :
        ?>
            <div class="row">
                <div class="col-md-5 panel panel-default panel-component">
                    <div class="panel-body">
                        <h3><i class="fa fa-caret-right"></i> <?= basename($comp['url']) ?></h3>

                        <p><?= $comp['description'] ?></p>
                    </div>

                    <div class="panel-footer">
                        <i class="fa fa-github"></i> <a href="https://github.com/zendframework/<?= basename($comp['url']) ?>" target="_blank">Github</a> -
                        <i class="fa fa-book"></i> <a href="<?= $comp['url'] ?>" target="_blank">Documentation</a>
                    </div>
                </div>

                <?php $comp = next($components) ?>

                <?php if ($comp) : ?>
                <div class="col-md-5 col-md-offset-1 panel panel-default panel-component">
                    <div class="panel-body">
                        <h3><i class="fa fa-caret-right"></i> <?= basename($comp['url']) ?></h3>

                        <p><?= $comp['description'] ?></p>
                    </div>

                    <div class="panel-footer">
                        <i class="fa fa-github"></i> <a href="https://github.com/zendframework/<?= basename($comp['url']) ?>" target="_blank">Github</a> -
                        <i class="fa fa-book"></i> <a href="<?= $comp['url'] ?>" target="_blank">Documentation</a>
                    </div>
                </div>
                <?php endif ?>
            </div>

            <div class="spacing"></div>
        <?php endwhile ?>
        </div>

        <div class="col-lg-4">
            <?= $this->render('include::learn-menu', [ 'active' => '/learn' ]) ?>
        </div>
    </div>
</div>
