<?php $this->headTitle('Participate'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Logos</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
          <h2>Logos</h2>
          <p>Our logos are licensed <a href="http://creativecommons.org/licenses/by-nc/3.0">CC BY-NC</a>; simply put, you can use them or modify them any way you want, as long as you attribute them to the Zend Framework project.</p>
          <div class="spacing"></div>
          <div class="row">
            <div class="col-lg-6">
              <img src="/images/logos/ZendFramework-logo.png">
            </div>
            <div class="col-lg-6">
              <a href="/images/logos/ZendFramework-logo.eps">EPS format</a><br />
              <a href="/images/logos/ZendFramework-logo.png">PNG format</a>
            </div>
          </div>
          <div class="spacing"></div>
          <div class="row">
            <div class="col-lg-6">
              <img src="/images/logos/zf-logo-mark.png">
            </div>
            <div class="col-lg-6">
              <a href="/images/logos/zf-logo-mark.eps">EPS format</a><br />
              <a href="/images/logos/zf-logo-mark.png">PNG format</a>
            </div>
          </div>
          <div class="spacing"></div>
          <div class="row">
            <div class="col-lg-6">
              <img src="/images/logos/zf-hero.png">
            </div>
            <div class="col-lg-6">
              <a href="/images/logos/zf-hero.png">PNG format</a>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::participate-menu', [ 'active' => '/participate/logos' ]) ?>
        </div>
      </div>
  </div>
