<?php $this->headTitle('Participate')->prepend('Logos'); ?>

<h2>Logos</h2>

<p>
    Our logos are licensed <a href="http://creativecommons.org/licenses/by-nc/3.0">CC BY-NC</a>;
    simply put, you can use them or modify them any way you want, as
    long as you attribute them to the Zend Framework project.
</p>

<div class="spacing"></div>

<div class="row">
    <div class="col-lg-6">
        <img src="/images/logos/ZendFramework-logo.png" alt="Zend Framework Logo">
    </div>

    <div class="col-lg-6">
        <a href="/images/logos/ZendFramework-logo.eps">EPS format</a><br/>
        <a href="/images/logos/ZendFramework-logo.png">PNG format</a>
    </div>
</div>

<div class="spacing"></div>

<div class="row">
    <div class="col-lg-6">
        <img src="/images/logos/zf-logo-mark.png" alt="Zend Framework Sign">
    </div>

    <div class="col-lg-6">
        <a href="/images/logos/zf-logo-mark.eps">EPS format</a><br/>
        <a href="/images/logos/zf-logo-mark.png">PNG format</a>
    </div>
</div>

<div class="spacing"></div>

<div class="row">
    <div class="col-lg-6">
        <img src="/images/logos/zf-hero.png" alt="Zend Framework Hero">
    </div>

    <div class="col-lg-6">
        <a href="/images/logos/zf-hero.png">PNG format</a>
    </div>
</div>

<?php $this->placeholder('sub-navigation')->set(
    $this->render('include::participate-menu', ['active' => '/participate/logos'])
) ?>
