<?php $this->headTitle('Documentation')->prepend('Manual'); ?>

<!-- Warning message -->
<p class="alert alert-warning" role="alert">
    <strong>Caution:</strong> The documentation you are viewing is
    for an older version of Zend Framework.<br>
    You can find the documentation of the current version at
    <a href="<?= $currentPageV3ComponentUrl ?? 'https://docs.zendframework.com/' ?>">
        <?= isset($currentPageV3ComponentUrl) ? substr($currentPageV3ComponentUrl, 8, -1) : 'docs.zendframework.com' ?>
    </a>
</p>

<p><?php echo $title ?></p>
<h1 id="component-name"><?php echo $currentPageTitle ?></h1>
<p>
    <?php echo $body ?>
</p>

<?php $this->placeholder('sub-navigation')->set(
    $this->render(
        'include::manual-sidebar', [
        'sidebar'       => $this->sidebar,
        'versions'      => $this->versions,
        'version'       => $this->version,
        'latestVersion' => $this->latestVersion,
        'contentList'   => $contentList,
        'currentPage'   => $currentPage,
        'lang'          => $this->lang,
        'page'          => $this->page,
    ]
    )
) ?>
