<?php $this->headTitle('Participate'); ?>

<h2>Zend Framework is a lot more than code, it's a community</h2>

<p>
    Zend Framework has hundreds of contributors and our users number in
    the hundreds of thousands. We can't thank this vibrant community
    enough for their many contributions of code, tests, documentation,
    and support over the years.
</p>

<p>Simply put: we haven't just built a framework together. We've built a community.</p>

<h3>Contributor Guide</h3>

<p>
    Learn how you can contribute effectively with the resources
    listed in our <a href="/participate/contributor-guide">contributor guide</a>,
    and our adopted code of conduct, the <a href="/participate/code-manifesto">Code Manifesto</a>.
</p>

<h3>Contributors</h3>

<p>
    Zend Framework's contributors have provided guidance, code,
    documentation, tests, and support for other community members since
    the inception of the project. You'll get a glimpse of a few of our
    contributors in our <a href="/participate/contributors">contributor gallery</a>.
</p>

<h4>Logos</h4>

<p>
    Want to advertise the fact that you're building with Zend
    Framework? Or are you presenting on a Zend Framework-related
    topic somewhere? Our logos are licensed <a href="http://creativecommons.org/licenses/by-nc/3.0">CC BY-NC</a>
    and can be found in our <a href="/participate/logos">logo gallery</a>.
</p>

<?php $this->placeholder('sub-navigation')->set(
    $this->render('include::participate-menu', ['active' => '/participate'])
) ?>
