<?php
$this->headTitle('Blog')->prepend($title);
$this->headLink()->appendAlternate('/blog/feed-rss.xml', 'application/rss+xml', 'Zend Framework Blog RSS Feed');
$this->headLink()->appendAlternate('/blog/feed-atom.xml', 'application/atom+xml', 'Zend Framework Blog Atom Feed');
?>

<!-- -- Blog Post  ---->
<h2><?= $title ?></h2>
<p class="blog-post__metadata"><?= date('Y-m-d', $date) ?> | By: <a href="<?= $url_author ?>"><?= $author ?></a></p>
<?php if (isset($updated)) : ?>
<p class="blog-post__metadata">Updated <?= is_numeric($updated) ? date('Y-m-d', $updated) : (new DateTime($updated))->format('Y-m-d') ?></p>
<?php endif ?>

<?= $body ?>

<div class="spacing"></div>

<h6>SHARE:</h6>

<p class="share">
    <a href="https://twitter.com/home?status=<?= urlencode(substr($title, 0, 50) . ', last post by @zfdevteam') ?>"
       target="_blank"><i class="fa fa-twitter fa-lg"></i></a>
    <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $this->serverUrl() ?>" target="_blank"><i class="fa fa-facebook fa-lg"></i></a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?= $this->serverUrl() ?>&title=<?= urlencode(
        $title . ', last post by Zend Framework project'
    ) ?>" target="_blank"><i class="fa fa-linkedin fa-lg"></i></a>
    <a href="https://plus.google.com/share?url=<?= $this->serverUrl() ?>" target="_blank"><i class="fa fa-google-plus fa-lg"></i></a>
</p>

<?php $this->placeholder('sub-navigation')->captureStart() ?>
<h4>Share</h4>
<div class="hline"></div>
<p class="share">
    <a href="https://twitter.com/home?status=<?= urlencode(substr($title, 0, 50) . ', last post by @zfdevteam') ?>"
       target="_blank"><i class="fa fa-twitter fa-lg"></i></a>
    <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $this->serverUrl() ?>" target="_blank"><i class="fa fa-facebook fa-lg"></i></a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?= $this->serverUrl() ?>&title=<?= urlencode(
        $title . ', last post by Zend Framework project'
    ) ?>" target="_blank"><i class="fa fa-linkedin fa-lg"></i></a>
    <a href="https://plus.google.com/share?url=<?= $this->serverUrl() ?>" target="_blank"><i class="fa fa-google-plus fa-lg"></i></a>
</p>

<div class="spacing"></div>

<h4>Subscribe</h4>
<div class="hline"></div>

<p class="rss-subscribe">Subscribe to this blog <a href="/blog/feed-rss.xml">via RSS</a>.</p>

<div class="spacing"></div>

<h4>Recent Posts</h4>
<div class="hline"></div>

<ul class="popular-posts">
    <?php foreach ($posts as $post) : ?>
        <li>
            <p><i class="fa fa-hand-o-right"></i> <a href="<?= $post['permalink'] ?>"><?= $post['title'] ?></a></p>
            <em><?= date('Y-m-d', $post['date']) ?></em>
        </li>
    <?php endforeach; ?>
</ul>
<?php $this->placeholder('sub-navigation')->captureEnd() ?>
