<?php $this->headTitle('Learn'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>MVC Skeleton Application</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>MVC Skeleton Application</h2>
            <p>If you want to use the <a href="https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">Model-View-Controller</a> (MVC) architecture for build your PHP application, you can use the skeleton provided by Zend Framework.</p>

            <h2>Installation using Composer</h2>

            <p>The easiest way to create a new Zend Framework project is to use <a href="https://getcomposer.org">Composer</a>.  If you don't have it already installed,
              then please install as per the <a href="https://getcomposer.org/doc/00-intro.md">documentation</a>.</p>

            <p>To create your new Zend Framework project:</p>

<pre><code class="language-bash">composer create-project -n -sdev zendframework/skeleton-application path/to/install</code></pre>

            <p>Once installed, you can test it out immediately using PHP's built-in web server:</p>

<pre><code class="language-bash">php -S 0.0.0.0:8080 -t public/ public/index.php</code></pre>

<p>This will start the cli-server on port 8080, and bind it to all network interfaces.<br />
<strong>Note:</strong> The built-in CLI server is <i>for development only</i>.</p>

            <h2>Using Vagrant</h2>

            <p>This skeleton includes a Vagrantfile based on Ubuntu 14.04, and using the ondrej/php PPA to provide PHP 7.0. Start it up using:

<pre><code class="language-bash">vagrant up</code></pre>

            <p>Once built, you can also run composer within the box. For example, the following
            will install dependencies:</p>

<pre><code class="language-bash">vagrant ssh -c 'composer install'</code></pre>

            <p>While this will update them:</p>

<pre><code class="language-bash">vagrant ssh -c 'composer update'</code></pre>

            <p>While running, Vagrant maps your host port 8080 to port 80 on the virtual
            machine; you can visit the site at http://localhost:8080/</p>

            <h2>Using docker-compose</h2>

            <p>This skeleton provides a docker-compose.yml for use with <a href="https://docs.docker.com/compose">docker-compose</a>; it
uses the Dockerfile provided as its base. Build and start the image using:

<pre><code class="language-bash">docker-compose up -d --build</code></pre>

            <p>At this point, you can visit http://localhost:8080 to see the site running.</p>

            <p>You can also run composer from the image. The container environment is named
            "zf", so you will pass that value to "docker-compose run":</p>

<pre><code class="language-bash">docker-compose run zf composer install</code></pre>

        </div>

        <div class="col-lg-4">
          <?php echo $this->render('include::download-menu', [ 'active' => '/downloads/skeleton-app' ]) ?>
        </div>
    </div>
</div>
