<?php $this->headTitle('Statistics'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Statistics</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-12">
            <h2>Statistics</h2>

            <p>
                This page contains the statistics of the Zend Framework
                component package installations from <a href="https://packagist.org">Packagist</a>.
                The packages are ordered by the total installation (from
                greatest to least).
            </p>
        </div>
    </div>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Package</th>
                <th class="right-text">Daily</th>
                <th class="right-text">Monthly</th>
                <th class="right-text">Total</th>
            </tr>
        </thead>

        <tbody>
        <?php foreach ($stats as $name => $value) :
            if (in_array($name, ['total', 'date'], true)) :
                continue;
            endif;
        ?>
            <tr>
                <td><a href="https://zendframework.github.io/<?= $name; ?>"><?= $name ?></a></td>
                <td class="right-text"><?= number_format($value['daily']) ?></td>
                <td class="right-text"><?= number_format($value['monthly']) ?></td>
                <td class="right-text"><?= number_format($value['total']) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <div class="spacing"></div>

    <div class="row">
        <div class="col-lg-12">
            Note: the installation numbers reported in this page are
            obtained using the <a href="https://packagist.org/apidoc">Packagist API</a>
            (last update: <?= date('Y-m-d H:i e', $stats['date']) ?>).
        </div>
    </div>
</div>
