<?php $this->headTitle('Status'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Status</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Package</th>
                <th class="center-text">Docs</th>
                <th class="center-text">Changelog</th>
                <th class="center-text">Travis</th>
                <th class="center-text">Master</th>
                <th class="center-text">Develop</th>
                <th class="center-text">Downloads</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($stats as $name => $value) :
            if (in_array($name, ['total', 'date'], true)) :
                continue;
            endif;
        ?>
            <tr>
                <td>
                    <a href="https://github.com/zendframework/<?= $name; ?>">
                        <?= $name; ?>
                    </a>
                </td>
                <td class="center-text">
                    <a href="https://zendframework.github.io/<?= $name; ?>">docs</a>
                </td>
                <td class="center-text">
                    <a href="https://zendframework.github.io/<?= $name; ?>/blob/master/CHANGELOG.md">changelog</a>
                </td>
                <td class="center-text">
                    <a href="https://secure.travis-ci.org/zendframework/<?= $name; ?>">
                        <img src="https://secure.travis-ci.org/zendframework/<?= $name; ?>.svg?branch=master">
                    </a>
                </td>
                <td class="center-text">
                    <a href="https://github.com/zendframework/<?= $name; ?>">
                        <img src="https://poser.pugx.org/zendframework/<?= $name; ?>/v/stable">
                    </a>
                </td>
                <td class="center-text">
                    <a href="https://github.com/zendframework/<?= $name; ?>/tree/develop">
                        <img src="https://poser.pugx.org/zendframework/<?= $name; ?>/v/unstable">
                    </a>
                </td>
                <td class="center-text">
                    <a href="https://github.com/zendframework/<?= $name; ?>/releases">
                        <img src="https://poser.pugx.org/zendframework/<?= $name; ?>/downloads">
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
