<?php $this->headTitle('Statistics'); ?>

<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Statistics</h3>
        </div>
    </div>
</div>

<div class="container mtb">
    <div class="row">
      <div class="col-lg-12">
        <h2>Statistics</h2>
        <p>This page contains the statistics of the Zend packages installation from <a href="https://packagist.org">Packagist</a>. The packages are ordered by the total installation (from greatest to least).</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3">
        <strong>Package</strong>
      </div>
      <div class="col-lg-3 text-right">
        <strong>Daily</strong>
      </div>
      <div class="col-lg-3 text-right">
        <strong>Monthly</strong>
      </div>
      <div class="col-lg-3 text-right">
        <strong>Total (<a href="">ordered by</a>)</strong>
      </div>
    </div>
    <?php
    $i = 0;
    foreach ($stats as $name => $value): ?>
      <?php if ($name === 'total' || $name === 'date') continue; ?>
      <div class="row" <?php if ($i++ % 2 === 0) echo 'style="background:#eeeeee"' ?>>
          <div class="col-lg-3">
            <a href="https://zendframework.github.io/<?php echo $name; ?>">
                <?php echo $name; ?>
            </a>
          </div>
          <div class="col-lg-3 text-right">
            <?php echo number_format($value['daily']) ?>
          </div>
          <div class="col-lg-3 text-right">
            <?php echo number_format($value['monthly']) ?>
          </div>
          <div class="col-lg-3 text-right">
            <?php echo number_format($value['total']) ?>
          </div>
      </div>
    <?php endforeach; ?>
    <div class="spacing"></div>
    <div class="row">
      <div class="col-lg-12">
        <p>Note: the installation numbers reported in this page are obtained using the <a href="https://packagist.org/apidoc">Packagist API</a> (last update: <?php echo date("Y-m-d H:i e", $stats['date']) ?>)</p>
      </div>
    </div>
</div>
