<?php $this->headTitle('Documentation')->prepend('Support & Consulting'); ?>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-8">
            <h2>Support & Consulting</h2>

            <p>Reduce business and technical risk and get peace of mind for your Zend Framework projects.</p>

            <div class="spacing"></div>

            <h2>Support</h2>

            <p>
                Zend Framework support delivers critical technical support that assists you during
                the development and production phases of the application lifecycle and helps to
                increase developer productivity while lowering time to deployment. It all adds up to
                success with your next Zend Framework project.
            </p>

            <p>For more information visit <a href="http://www.zend.com/en/support-center/support/">Zend Support</a>.</p>

            <div class="spacing"></div>

            <h2>Consulting</h2>

            <p>
                Whether you have a time-sensitive project or need a custom component, Zend
                Technologies offers a wide range of consulting services for PHP and Zend Framework.
            </p>

            <p>Visit <a href="http://www.zend.com/en/services/consulting/">Zend Consulting</a> for more information.</p>

            <div class="spacing"></div>

            <a href="http://www.zend.com"><img src="/img/zend-logo.png" alt="Zend, a Rogue Wave Company" title="Zend, a Rogue Wave Company" align="left"></a>
        </div>

        <?php $this->placeholder('sub-navigation')->set(
            $this->render('include::learn-menu', [ 'active' => '/learn/support-and-consulting' ])
        ) ?>
    </div>
</div>
