<?php
$links = [
  '/about'             => 'About',
  '/about/faq'         => 'FAQ',
  '/license'           => 'License',
  '/long-term-support' => 'Long Term Support',
  '/changelog'         => 'Changelog'
];
?>

<ul class="nav nav-pills nav-stacked">
    <?php foreach ($links as $url => $title) : ?>
    <li<?= ($url === $active) ? ' class="active"' : '' ?>>
        <a href="<?= $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?= $title ?></a>
    </li>
    <?php endforeach; ?>
</ul>
