<?php
$languages    = $this->releases->getManualLanguages($this->version);
$languageKeys = array(
    'en' => 'English',
    'de' => 'Deutsch (German)',
    'fr' => 'Français (French)',
    'ru' => 'Русский (Russian)',
    'ja' => '日本語 (Japanese)',
    'zh' => '简体中文 (Simplified Chinese)',
);
?>

<?php foreach ($languages as $language): ?>
  <?php echo ($languageKeys[$language]) ?>:
  <a href="<?php echo $this->releases->getManualArchive($this->version, $language, 'zip') ?>">zip</a>, <a href="<?php echo $this->releases->getManualArchive($this->version, $language, 'tar.gz') ?>">tar.gz</a><br />
<?php endforeach; ?>
