<?php
$links = [
    '/downloads'              => 'Install',
    '/downloads/skeleton-app' => 'MVC skeleton app',
    '/downloads/expressive'   => 'Expressive skeleton app',
    '/downloads/archives'     => 'Archives',
];
$path = parse_url($this->serverUrl(), PHP_URL_PATH);
?>

<ul class="nav nav-pills nav-stacked">
<?php foreach ($links as $url => $title) : ?>
    <li<?= ($url === $active) ? ' class="active"' : '' ?>>
        <a href="<?= $url ?>"><span class="glyphicon glyphicon-chevron-right"></span>&nbsp;<?= $title ?></a>
    </li>
<?php endforeach ?>
</ul>
