<?php
$links = [
  '/downloads'     => 'Install',
  '/downloads/skeleton-app' => 'MVC skeleton app',
  '/downloads/expressive' => 'Middleware skeleton app',
  '/downloads/archives' => 'Archives',
];
$path = parse_url($this->serverUrl(), PHP_URL_PATH);
?>

<ul class="nav nav-pills nav-stacked">
  <?php foreach($links as $url => $title): ?>
      <li <?php if ($url === $active) echo 'class="active"' ?>>
        <a href="<?php echo $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?php echo $title ?></a>
      </li>
  <?php endforeach; ?>
</ul>
