<div id="footerwrap">
    <div class="container">
        <div class="row site-map">
            <div class="col-lg-3">
              <p>
                <strong>About</strong><br />
                <a href="/about">Overview</a><br />
                <a href="/about/faq">FAQ</a><br />
                <a href="/license">License</a><br />
                <a href="/long-term-support">Long Term Support</a><br />
                <a href="/changelog">Changelog</a><br />
                <a href="/security">Security</a><br />
                <a href="/issues">Issues</a>
              </p>
            </div>

            <div class="col-lg-3">
              <p>
                <strong>Install</strong><br />
                <a href="/downloads">Get started</a><br />
                <a href="/downloads/skeleton-app">MVC skeleton app</a><br />
                <a href="/downloads/expressive">Expressive skeleton app</a><br />
                <a href="/downloads/archives">Archives</a><br />
                <a href="/stats">Statistics</a><br/>
              </p>
            </div>

            <div class="col-lg-3">
              <p>
                <strong>Documentation</strong><br />
                <a href="/learn">Overview</a><br />
                <a href="/learn/training-and-certification/">Training and Certification</a><br />
                <a href="/learn/support-and-consulting/">Support and Consulting</a><br />
                <a href="http://www.zend.com/en/webinars/recorded/show-by-topic/242_zend+framework">Webinars</a><br />
                <a href="/blog">Blog</a><br />
                <a href="/manual/2.4/en/index.html">Zend Framework 2</a> - <a href="/docs/api/zf2">API</a><br />
                <a href="/manual/1.12/en/manual.html">Zend Framework 1</a> - <a href="/docs/api/zf1">API</a><br/>
              </p>
            </div>

            <div class="col-lg-3">
              <p>
                <strong>Participate</strong><br />
                <a href="/participate">Overview</a><br />
                <a href="https://zendframework-slack.herokuapp.com">Slack</a><br />
                <a href="https://discourse.zendframework.com">Forums</a><br />
                <a href="https://tinyletter.com/mwopzend">Newsletter</a><br />
                <a href="/participate/contributor-guide">Contributor guide</a><br />
                <a href="/participate/code-manifesto">Code Manifesto</a><br />
                <a href="/participate/contributors">Contributors</a><br />
                <a href="/participate/logos">Logos</a><br />
                <a href="/status">Status</a><br />
                <a href="http://www.zend.com/en/services/certification">Get certified</a>
              </p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 centered">
                <a class="back-to-top"><i class="fa fa-chevron-circle-up fa-4" aria-hidden="true"></i></a>
            </div>
        </div>

        <div class="spacing"></div>

        <div class="row">
            <div class="col-lg-8">
                <h4>Copyright</h4>
                <div class="hline-w"></div>

                <p>&copy; 2006-<?= date("Y") ?> by <a href="http://www.zend.com">Zend</a>, a <a href="http://www.roguewave.com/">Rogue Wave Company</a>. Made with <i class="fa fa-heart"></i> by awesome <a href="/participate/contributors">contributors</a>.</p>

                <p>This website is built using <a href="https://github.com/zendframework/zend-expressive">zend-expressive</a> and it runs on <a href="http://www.zend.com/en/resources/php-7">PHP 7</a>.</p>
            </div>

            <div class="col-lg-4">
                <h4>Contacts</h4>
                <div class="hline-w"></div>
                <p>
                    <a href="https://zendframework-slack.herokuapp.com" class="btn-social btn-outline" title="Slack"><i class="fa fa-slack"></i></a>
                    <a href="https://github.com/zendframework" class="btn-social btn-outline" title="Github"><i class="fa fa-github"></i></a>
                    <a href="https://twitter.com/zfdevteam" class="btn-social btn-outline" title="Twitter"><i class="fa fa-twitter"></i></a>
                    <a href="https://tinyletter.com/mwopzend" class="btn-social btn-outline" title="Newsletter"><i class="fa fa-envelope"></i></a>
                    <a href="/blog/feed-rss.xml" class="btn-social btn-outline" title="Blog feed"><i class="fa fa-rss"></i></a>
                    <a href="/security/feed" class="btn-social btn-outline" title="Security feed"><i class="fa fa-rss-square"></i></a>
                </p>
            </div>
        </div>
    </div>
</div>
