<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Zend Framework project official website">
    <meta name="author" content="Zend, a Rogue Wave Company">
    <link rel="shortcut icon" href="/ico/favicon.ico">

    <title><?= $this->headTitle('Zend Framework')->setSeparator(' - ') ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/prism.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/main.css?201606301756">
    <?php if (false !== strpos(parse_url($this->serverUrl(), PHP_URL_PATH), '/manual')) : ?>
    <link rel="stylesheet" href="/css/manual.css">
    <?php endif; ?>

    <?= $this->headLink() ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
