<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Zend Framework project official website">
    <meta name="author" content="Zend, a Rogue Wave Company">
    <link rel="shortcut icon" href="/ico/favicon.ico">

    <?= $this->headTitle('Zend Framework')->setSeparator(' - ') ?>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/<?= $this->asset('css/styles.css') ?>">
    <?php if (false !== strpos(parse_url($this->serverUrl(), PHP_URL_PATH), '/manual')) : ?>
    <link rel="stylesheet" href="/<?= $this->asset('css/manual.css') ?>">
    <?php endif; ?>

    <?= $this->headLink() ?>
</head>
