<?php
$links = [
    '/issues'     => 'Overview',
    '/issues/ZF2' => 'ZF2 Issue Archive',
    '/issues/ZF1' => 'ZF1 Issue Archive'
];
$path = parse_url($this->serverUrl(), PHP_URL_PATH);
?>

<ul class="nav nav-pills nav-stacked">
<?php foreach ($links as $url => $title) : ?>
    <li<?= ($url ===  $active) ? ' class="active"' : '' ?>>
        <a href="<?= $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?= $title ?></a>
    </li>
<?php endforeach ?>
</ul>

<div class="spacing"></div>

<div>
    <p><i class="fa fa-github fa-2x"></i> Have you found an issue?</p>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#issueModal">Please report here!</button>
</div>

<p>See the <a href="/issues">Overview</a> section for more details.</p>

<?= $this->render('include::modal-issue', [ 'repository' => $repository ]) ?>
