<?php
$links = [
  '/issues'     => 'Overview',
  '/issues/ZF2' => 'ZF2 Issue Archive',
  '/issues/ZF1' => 'ZF1 Issue Archive'
];
$path = parse_url($this->serverUrl(), PHP_URL_PATH);
?>

<ul class="nav nav-pills nav-stacked">
  <?php foreach($links as $url => $title): ?>
      <li <?php if ($url === $active) echo 'class="active"' ?>>
        <a href="<?php echo $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?php echo $title ?></a>
      </li>
  <?php endforeach; ?>
</ul>

<div class="spacing"></div>
<p><i class="fa fa-github fa-2x"></i> Did you find an issue in Zend Framework?<br />
Please report it on <a href="https://github.com/zendframework/">Github</a> choosing the specific component repository, thanks!</p>
<p>See the <a href="/issues">Overview</a> section for more details.</p>
