<div id="select-version">
    <label for="version">Select a version:</label>
    <select class="form-control" id="version">
        <?php foreach ($this->versions as $ver) : ?>
            <option
                value="<?= $ver ?>"
                <?= ($ver === $this->version) ? ' selected="selected"' : '' ?>>
              Version <?= $ver ?>
            </option>
        <?php endforeach ?>
    </select>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
    $('#select-version select').change(function(){
        $.ajax({
            type: 'post',
            url: '/switch-manual',
            data: JSON.stringify({
                old  : '$version',
                new  : $(this).val(),
                lang : '$lang',
                page : '$page'

            }),
            success: function(data){
              location.href = data.url;
            },
            contentType: 'application/json; charset=utf-8',
            dataType: 'json'
        });
    });
JS;
$this->inlineScript()->captureEnd();
?>

<?php if (count($contentList)) : ?>
    <div id="select-chapter">
        <label for="chapter">Select chapter:</label>
        <select class="form-control" id="chapter">
            <?php foreach ($contentList as $headline => $items) : ?>

                <?php if (is_array($items)) : ?>
                    <optgroup label="<?= $headline ?>">
                        <?php foreach ($items as $link => $label) : ?>
                            <option value="<?= $link ?>"<?= ($currentPage === $link)?' selected="selected"':'' ?>>
                                <?= $label ?>
                            </option>
                        <?php endforeach ?>
                    </optgroup>
                <?php else : ?>
                    <option value="<?= $headline ?>"<?= ($currentPage === $headline)?' selected="selected"':'' ?>>
                        <?= $items ?>
                    </option>
                <?php endif ?>

            <?php endforeach ?>
        </select>
    </div>

    <?php
    $basePath = sprintf('/manual/%s/en/', $this->version);
    $this->inlineScript()->captureStart();
    echo <<<JS
    $('#select-chapter select').change(function(){
        location.href = '$basePath' + $(this).val();
    });
JS;
    $this->inlineScript()->captureEnd();
endif ?>

<div id="toc">
    <?= $sidebar; ?>
</div>

<div class="zf2a-course">
    <a href="http://www.zend.com/en/services/certification/framework-2/">
        <img src="/img/ZF2-Certification-390x300px.png" alt="New! Zend Framework 2 Certification">
    </a>
</div>
