<?php
$url = parse_url($this->serverUrl(), PHP_URL_PATH);
?>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/img/zf-logo-mark.png"> Zend Framework</a>
        </div>

        <div class="navbar-collapse collapse navbar-right">
            <ul class="nav navbar-nav">
                <li<?= (false !== strpos($url, '/about')
                    || false !== strpos($url, '/license')
                    || false !== strpos($url, '/long-term-support')
                    || false !== strpos($url, '/changelog')) ? ' class="active"' : '' ?>><a href="/about">ABOUT</a></li>
                <li<?= (false !== strpos($url, '/downloads')) ? ' class="active"' : '' ?>><a href="/downloads">INSTALL</a></li>
                <li<?= (false !== strpos($url, '/learn')
                    || false !== strpos($url, '/manual')
                    || false !== strpos($url, '/docs')) ? ' class="active"' : '' ?>><a href="/learn">DOCUMENTATION</a></li>
                <li><a href="http://www.zend.com/en/services/certification">GET CERTIFIED</a></li>
                <li<?= (false !== strpos($url, '/blog')) ? ' class="active"' : '' ?>><a href="/blog">BLOG</a></li>
                <li<?= (false !== strpos($url, '/participate')) ? ' class="active"' : '' ?>><a href="/participate">PARTICIPATE</a></li>
            </ul>
        </div>
    </div>
</div>
