<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <a id="github-link" href="https://github.com/zendframework">
      <img src="https://github-camo.global.ssl.fastly.net/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png">
    </a>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="/img/zf-logo-mark.png"> Zend Framework 3</a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <?php $url = parse_url($this->serverUrl(), PHP_URL_PATH); ?>
        <li <?php if (false !== strpos($url, '/about') ||
                      false !== strpos($url, '/license') ||
                      false !== strpos($url, '/long-term-support') ||
                      false !== strpos($url, '/changelog')) echo 'class="active"' ?>><a href="/about">ABOUT</a></li>
        <li <?php if (false !== strpos($url, '/downloads')) echo 'class="active"' ?>><a href="/downloads">INSTALL</a></li>
        <li <?php if (false !== strpos($url, '/learn') ||
                      false !== strpos($url, '/manual') ||
                      false !== strpos($url, '/docs')) echo 'class="active"' ?>><a href="/learn">DOCUMENTATION</a></li>
        <li><a href="http://www.zend.com/en/services/certification">GET CERTIFIED</a></li>
        <li <?php if (false !== strpos($url, '/blog')) echo 'class="active"' ?>><a href="/blog">BLOG</a></li>
        <li <?php if (false !== strpos($url, '/participate')) echo 'class="active"' ?>><a href="/participate">PARTICIPATE</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
