<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="/img/zf-logo-mark.png"> Zend Framework 3</a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li {% if page.url contains '/about/' %}class="active"{% endif %}><a href="/about">ABOUT</a></li>
        <li {% if page.url contains '/install/' %}class="active"{% endif %}><a href="/install">INSTALL</a></li>
        <li {% if page.url contains '/learn/' %}class="active"{% endif %}><a href="/learn">DOCUMENTATION</a></li>
        <li {% if page.url contains '/certification/' %}class="active"{% endif %}><a href="http://www.zend.com/en/services/certification">GET CERTIFIED</a></li>
        <li {% if page.url contains '/blog/' %}class="active"{% endif %}><a href="/blog">BLOG</a></li>
        <li {% if page.url contains '/participate/' %}class="active"{% endif %}><a href="/participate">PARTICIPATE</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
