<?php
$links = [
  '/participate'                   => 'Overview',
  '/participate/contributor-guide' => 'Contributor Guide',
  '/participate/contributors'      => 'Contributors',
  '/participate/logos'             => 'Logos'
];
?>

<ul class="nav nav-pills nav-stacked">
  <?php foreach($links as $url => $title): ?>
      <li <?php if ($url === $active) echo 'class="active"' ?>>
        <a href="<?php echo $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?php echo $title ?></a>
      </li>
  <?php endforeach; ?>
</ul>
