<?php
$links = [
    '/participate'                   => 'Overview',
    '/participate/contributor-guide' => 'Contributor Guide',
    '/participate/code-manifesto'    => 'Code Manifesto',
    '/participate/contributors'      => 'Contributors',
    '/participate/logos'             => 'Logos',
];
?>

<ul class="nav nav-pills nav-stacked">
<?php foreach ($links as $url => $title) : ?>
    <li<?= ($url === $active) ? ' class="active"' : '' ?>>
        <a href="<?= $url ?>"><span class="glyphicon glyphicon-chevron-right"></span>&nbsp;<?= $title ?></a>
    </li>
<?php endforeach ?>
</ul>
