<?php
$links = [
  '/security'            => 'Overview',
  '/security/advisories' => 'Advisories',
  '/security/feed'      => 'Feed'
];
$path = parse_url($this->serverUrl(), PHP_URL_PATH);
?>

<ul class="nav nav-pills nav-stacked">
  <?php foreach($links as $url => $title): ?>
      <li <?php if ($path === $url) echo 'class="active"' ?>>
        <a href="<?php echo $url ?>"><span class="glyphicon glyphicon-chevron-right"></span> <?php echo $title ?></a>
      </li>
  <?php endforeach; ?>
</ul>

<div class="spacing"></div>
<p><i class="fa fa-bug fa-2x"></i> Did you find a security vulnerability in ZF?<br />
Please report it to us at <a href="mailto:zf-security@zend.com">zf-security@zend.com</a></p>
