<?php $this->headTitle('404 Not Found'); ?>

<div class="container mtb">
    <div class="row">
        <div class="col-lg-12">
          <h1>Oops!</h1>
          <h2>This is awkward.</h2>
          <p>We encountered a 404 Not Found error.</p>
          <p>
              You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
              or head back to <a href="<?php echo $this->url('home') ?>">Home</a>.
          </p>
        </div>
      </div>
</div>
