<?php
$this->headLink()
    ->appendAlternate('/security/feed', 'application/rss+xml', 'Zend Framework Security Advisories')
    ->appendAlternate('/blog/feed-atom.xml', 'application/atom+xml', 'Zend Framework Blog Atom Feed')
    ->appendAlternate('/blog/feed-rss.xml', 'application/rss+xml', 'Zend Framework Blog RSS Feed')
    ->appendAlternate('/releases/atom.xml', 'application/atom+xml', 'Zend Framework Releases Atom Feed')
    ->appendAlternate('/releases/rss.xml', 'application/rss+xml', 'Zend Framework Releases RSS Feed');

$this->inlineScript()
    ->prependFile('/js/prism.js')
    ->prependFile('/js/custom.js')
    ->prependFile('/js/jquery.isotope.min.js')
    ->prependFile('/js/jquery.prettyPhoto.js')
    ->prependFile('/js/jquery.hoverex.min.js')
    ->prependFile('/js/jquery.hoverdir.js')
    ->prependFile('/js/retina-1.1.0.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js');
?>
<!DOCTYPE html>
<html class="csstransforms no-csstransforms3d csstransitions">
<?php echo $this->render('include::head') ?>
<body<?= (false !== strpos(parse_url($this->serverUrl(), PHP_URL_PATH), '/manual')) ? ' id="manual"' : '' ?>>
    <?php echo $this->render('include::nav') ?>

    <!-- Headline -->
    <?php $offset = $this->headTitle()->count() - 2 ?>
    <?php if ($this->headTitle()->offsetExists($offset)
              && $this->headTitle()->offsetGet($offset) !== 'Home') : ?>
        <div id="blue">
            <div class="container">
                <div class="row">
                    <h3><?= $this->headTitle()->offsetGet($offset) ?></h3>
                </div>
            </div>
        </div>
    <?php endif ?>

    <?php if ((string) $this->placeholder('page-layout') === 'wide') : ?>
        <?php echo $this->content ?>
    <?php else : ?>
        <div class="container mtb">
            <div class="row">
                <!-- Content -->
                <div class="col-lg-8">
                    <?php echo $this->content ?>
                </div>

                <!-- Sub-navigation -->
                <div class="col-lg-4">
                    <?= $this->placeholder('sub-navigation') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <?php echo $this->render('include::footer') ?>

    <?php echo $this->inlineScript(); ?>

    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PG5L5N"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PG5L5N');</script>
    <!-- End Google Tag Manager -->
</body>
</html>
