<?php
$this->headLink()
    ->appendAlternate('/security/feed', 'application/rss+xml', 'Zend Framework Security Advisories')
    ->appendAlternate('/blog/feed-atom.xml', 'application/atom+xml', 'Zend Framework Blog Atom Feed')
    ->appendAlternate('/blog/feed-rss.xml', 'application/rss+xml', 'Zend Framework Blog RSS Feed')
    ->appendAlternate('/releases/atom.xml', 'application/atom+xml', 'Zend Framework Releases Atom Feed')
    ->appendAlternate('/releases/rss.xml', 'application/rss+xml', 'Zend Framework Releases RSS Feed');

$this->inlineScript()
    ->prependFile('/' . $this->asset('js/scripts.js'))
    ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js')
    ->prependFile('https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js');
?>
<!DOCTYPE html>
<html>
<?php echo $this->render('include::head') ?>
<body<?= (false !== strpos(parse_url($this->serverUrl(), PHP_URL_PATH), '/manual')) ? ' id="manual"' : '' ?>>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T36WFBL"  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PG5L5N"  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <?php echo $this->render('include::nav') ?>

    <!-- Headline -->
    <?php $offset = $this->headTitle()->count() - 2 ?>
    <?php if ($this->headTitle()->offsetExists($offset)
              && $this->headTitle()->offsetGet($offset) !== 'Home') : ?>
        <div id="blue">
            <div class="container">
                <div class="row">
                    <h3><?= $this->headTitle()->offsetGet($offset) ?></h3>
                </div>
            </div>
        </div>
    <?php endif ?>

    <?php if ((string) $this->placeholder('page-layout') === 'wide') : ?>
        <?php echo $this->content ?>
    <?php else : ?>
        <div class="container mtb">
            <div class="row">
                <!-- Content -->
                <div class="col-lg-8">
                    <?php echo $this->content ?>
                </div>

                <!-- Sub-navigation -->
                <div class="col-lg-4">
                    <?= $this->placeholder('sub-navigation') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <?php echo $this->render('include::footer') ?>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
