<?php
$this->inlineScript()
    ->prependFile('/js/prism.js')
    ->prependFile('/js/custom.js')
    ->prependFile('/js/jquery.isotope.min.js')
    ->prependFile('/js/jquery.prettyPhoto.js')
    ->prependFile('/js/jquery.hoverex.min.js')
    ->prependFile('/js/jquery.hoverdir.js')
    ->prependFile('/js/retina-1.1.0.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js');
?>
<!DOCTYPE html>
<html class="csstransforms no-csstransforms3d csstransitions">
<?php echo $this->render('include::head') ?>
<body <?php if (false !== strpos(parse_url($this->serverUrl(), PHP_URL_PATH), '/manual')) echo 'id="manual"' ?>>
    <?php echo $this->render('include::nav') ?>

    <?php echo $this->content ?>

    <?php echo $this->render('include::footer') ?>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
